### ISSUE TITLE
Having trouble running the application

### ISSUE THREAD

**Issue by nnacin** [joaomilho/apalachin#4]
I get db_connection_down when trying to add a new user.

And in the browser this:
We got a problem!
This message will appear in production; you may want to define a 500 handler in /home/mininet/Downloads/apalachin/priv/chat.routes
Error:

"Error in controller, see console.log for details\n"

etc.

**Comment by joaomilho** [comment]
Can you provide more info?

Was the db created correctly? Migrations ran ok? What are the versions of Erlang/Apalachin?

**Comment by nnacin** [comment]
I got past this error.
I was able to start the chat app. Login some user, but in the terminal I read those errors:
[error] gen_server chat_chat_protocol_websocket terminated with reason: "Auth"
10:45:41.543 [error] CRASH REPORT Process <0.287.0> with 0 neighbours exited with reason: "Auth" in gen_server:terminate/7 line 804
10:45:41.544 [error] Supervisor {global,boss_service_sup} had child chat_chat_protocol_websocket started with boss_service_worker:start_link(chat_chat_protocol_websocket, <<"/websocket/chat_protocol">>) at <0.287.0> exit with reason "Auth" in context child_terminated

although the application is still running.
But the messages are not being exchanged between the users.
The db was created correctly and the migrations ran ok.

**Comment by ourway** [comment]
No message exchange!

**Comment by joaomilho** [comment]
Oh, I'll give a try today. Sorry for the huge delay.

**Comment by joaomilho** [comment]
So, @nnacin & @ourway, the problem was related to an API update in ChicagoBoss from 0.8.7 to 0.8.19.

I fixed it and updated instructions to use the new version.
